# Generated by Django 5.2 on 2025-06-30 18:47

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('ABANDONED', 'abandoned'), ('CONVERTED', 'converted')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 7, 3, 18, 46, 41, 318269, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('PAID', 'paid'), ('SHIPPED', 'shipped'), ('CANCELLED', 'cancelled'), ('REFUNDED', 'refunded')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('prescription_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_order', 'can manage orders')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('form', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
