# Generated by Django 5.2 on 2025-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('ABANDONED', 'abandoned'), ('CONVERTED', 'converted')], default='ACTIVE', max_length=20),
        ),
    ]
