# Generated by Django 5.2 on 2025-06-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='produits.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('batch_number', models.CharField(max_length=100)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('LIQUID', 'Liquid'), ('CREAM', 'Cream'), ('INJECTION', 'injection'), ('DROPS', 'Drops')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'batch_number'], name='produits_pr_name_bab740_idx'), models.Index(fields=['expiry_date'], name='produits_pr_expiry__e1bd37_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_lte_total')],
            },
        ),
    ]
