# Generated by Django 5.2 on 2025-05-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('productDate', models.DateField(auto_now_add=True)),
                ('expiryDate', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.category')),
            ],
            options={
                'ordering': ['-productDate'],
            },
        ),
    ]
