# Generated by Django 5.2 on 2025-06-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_product_productdate_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
